version: '3.8'

services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: react-app
    ports:
      - "4321:4321" 
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro.rule=Host(`cicd-front.louisdev.fr`)"
      - "traefik.http.routers.astro.entrypoints=websecure"
      - "traefik.http.services.astro.loadbalancer.server.port=3001"
      - "traefik.http.routers.astro.service=dash"
      - "traefik.http.routers.astro.tls.certresolver=leresolver"
    networks:
      - traefik

networks:
  traefik:
    external: true
